# Random Forests

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import math
import random

%matplotlib inline
pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None 

rand_seed = 123
random.seed(rand_seed)
np.random.seed(rand_seed)

In [2]:
train = pd.read_csv("train.csv")
validation = pd.read_csv("validation.csv")
test = pd.read_csv("test.csv")

## Feature Engineering

In [9]:
def UsertagCategories(df):
    
    df = df["usertag"].dropna().reset_index(drop = True)
    usertags_list = [df[i].split(",") for i in range(df.shape[0])]
    usertags = np.unique(list(itertools.chain.from_iterable(usertags_list)))
    usertags = [tag for tag in usertags if len(tag) > 0]
    
    return usertags

In [10]:
usertags_train = UsertagCategories(train)
usertags_validation = UsertagCategories(validation)

In [12]:
def FeatureEngineering(df):
    
        # Convert numerical to categorical
        df["weekday_cat"] = df["weekday"].map(lambda x: str(x))
        df["hour_cat"] = df["hour"].map(lambda x: str(x))
        df["region_cat"] = df["region"].map(lambda x: str(x))
        df["city_cat"] = df["city"].map(lambda x: str(x))
        df["adexchange_cat"] = df["adexchange"].map(lambda x: str(x))
        df["advertiser_cat"] = df["advertiser"].map(lambda x: str(x))
        
        # Operating system
        df["os"] = df["useragent"].map(lambda x: x.split("_")[0])
        
        # Browser
        df["browser"] = df["useragent"].map(lambda x: x.split("_")[1])
        
        # Slotarea
        df["slotarea"] = df["slotwidth"]*df["slotheight"]   ####.astype("category")
       
        # Slotprice binning
        df["slotprice_cat"] = 0
        
        df.loc[ df["slotprice"] <= 10, "slotprice_cat"] = 0
        df.loc[ (df["slotprice"] > 10) & (df["slotprice"] <= 50), "slotprice_cat"] = 1
        df.loc[ (df["slotprice"] > 50) & (df["slotprice"] <= 100), "slotprice_cat"] = 2
        df.loc[ df["slotprice"] > 100, "slotprice_cat"] = 3

        
        # Usertags
        
        df['usertag'] = df['usertag'].astype(str)
        for tag in usertags_train:
            col_name = "usertag_" + tag
            df[col_name] = df["usertag"].map(lambda x: 1 if tag in x.split(",") else 0)
        
  
        return df


def DropColumns(df):
    
    columns = ["weekday", "hour", "bidid", "userid", "useragent", "IP", "domain", "url", "urlid", "slotid",
               "slotwidth", "slotheight", "keypage", "usertag", "region", "city", "adexchange", "advertiser"]
    df.drop(columns, axis = 1, inplace = True)
    
    return df


def GetDummies(df):
    
    df = pd.get_dummies(df)
    return df

In [13]:
all_data = pd.concat((train, validation), axis = 0)

In [15]:
all_data = FeatureEngineering(all_data)

In [17]:
# Drop useless features
all_data = DropColumns(all_data)

In [18]:
all_data = all_data.drop(columns = ['creative'])

In [19]:
all_data.shape

(2734906, 85)

In [21]:
# Convert categorical features to numerical using dummy variables
all_data_dummy = GetDummies(all_data)

In [22]:
c = all_data_dummy.columns
c

Index(['click', 'slotprice', 'bidprice', 'payprice', 'slotarea',
       'slotprice_cat', 'usertag_10006', 'usertag_10024', 'usertag_10031',
       'usertag_10048',
       ...
       'part_of_the_day_Saturday_Night', 'part_of_the_day_Sunday_Evening',
       'part_of_the_day_Sunday_Morning', 'part_of_the_day_Sunday_Night',
       'part_of_the_day_Tuesday_Evening', 'part_of_the_day_Tuesday_Morning',
       'part_of_the_day_Tuesday_Night', 'part_of_the_day_Wednesday_Evening',
       'part_of_the_day_Wednesday_Morning', 'part_of_the_day_Wednesday_Night'],
      dtype='object', length=572)

In [23]:
all_data_dummy.head()

click  slotprice  bidprice  payprice  slotarea  slotprice_cat  \
0      0          5       238         5     40000              0   
1      0          0       294        23     75000              0   
2      0          5       238        24     62500              0   
3      0          0       300        25     96000              0   
4      0        133       277       133     65520              3   

   usertag_10006  usertag_10024  usertag_10031  usertag_10048  usertag_10052  \
0              0              0              0              0              0   
1              0              0              0              0              0   
2              1              0              0              0              1   
3              0              0              0              0              0   
4              0              0              0              0              0   

   usertag_10057  usertag_10059  usertag_10063  usertag_10067  usertag_10074  \
0              0              0              0              0              0   
1              0              0              0              0              0   
2              0              0              0              0              0   
3              0              0              1              0              0   
4              0              0              0              0              0   

   usertag_10075  usertag_10076  usertag_10077  usertag_10079  usertag_10083  \
0              0              0              0              0              0   
1              0              0              0              0              0   
2              0              0              0              0              0   
3              0              0              0              0              0   
4              0              0              0              0              0   

   usertag_10093  usertag_10102  usertag_10110  usertag_10111  usertag_10114  \
0              0              0              0              0              0   
1              0              0              0              0              0   
2              0              0              1              0              0   
3              0              0              0              1              0   
4              0              0              0              0              0   

   usertag_10115  usertag_10116  usertag_10117  usertag_10118  usertag_10120  \
0              0              0              0              0              0   
1              0              0              0              0              0   
2              0              0              0              0              0   
3              0              0              0              0              0   
4              0              0              0              0              0   

   usertag_10123  usertag_10125  usertag_10126  usertag_10127  usertag_10129  \
0              0              0              0              0              0   
1              0              0              0              0              0   
2              0              0              0              0              0   
3              0              0              0              0              0   
4              0              0              0              0              0   

   usertag_10130  usertag_10131  usertag_10133  usertag_10138  usertag_10140  \
0              0              0              0              0              0   
1              0              0              0              0              0   
2              0              0              0              0              0   
3              0              0              0              0              0   
4              0              0              0              0              0   

   usertag_10142  usertag_10145  usertag_10146  usertag_10147  usertag_10148  \
0              0              0              0              0              0   
1              0              0              0              0      

In [24]:
train_dummy = all_data_dummy[:train.shape[0]]
validation_dummy = all_data_dummy[train.shape[0]:]

In [25]:
train_dummy.shape, validation_dummy.shape

((2430981, 572), (303925, 572))

## Downsampling

In [30]:
train_majority = train_dummy[train_dummy.click==0]
train_minority = train_dummy[train_dummy.click==1]
train_minority.shape[0] 

1793

In [31]:
w = 0.0073 # class 0, downsampling rate

train_majority_downsampled = train_majority.sample(n = int(w * train_majority.shape[0]), 
                                                         replace=False, random_state=1)
print(len(train_majority_downsampled))

train = pd.concat([train_majority_downsampled, train_minority]).sample(frac=1)
print(len(train))

17733
19526


In [32]:
train.shape

(19526, 572)

In [33]:

X = train.loc[:, ((train.columns != "click") & 
                          (train.columns != "payprice") &
                          (train.columns != "bidprice") &
                          (train.columns != "slotprice"))].values
y = train["click"].values

X_validation = validation_dummy.loc[:, ((validation_dummy.columns != "click") & 
                                            (validation_dummy.columns != "payprice") & 
                                            (validation_dummy.columns != "bidprice") &
                                            (train.columns != "slotprice"))]
y_validation = validation_dummy["click"]
    


In [34]:
X.shape, y.shape, X_validation.shape, y_validation.shape

((19526, 568), (19526,), (303925, 568), (303925,))

In [35]:
clicks = train.loc[train["click"] == 1].shape[0]


## Random Forests


In [36]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

#### Grid-search for the best parameters

In [37]:
# rfc=RandomForestClassifier(random_state=42)

# param_grid = {    
#     'n_estimators': [100, 200, 500],
#     'max_features': ['auto', 'sqrt', 'log2'],
#     'max_depth' : [4,5,6,7,8],
#     'criterion' :['gini', 'entropy']
# }

# CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
# CV_rfc.fit(X, y)

# CV_rfc.best_params_

In [38]:
clf = RandomForestClassifier(random_state=42, max_features='auto', n_estimators= 100, max_depth=7, criterion='entropy', 
                             class_weight= 'balanced')

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X,y)


RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='entropy', max_depth=7, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=None, oob_score=False,
            random_state=42, verbose=0, warm_start=False)

In [39]:
y_pred=clf.predict(X_validation)

In [40]:
from sklearn import metrics

print (metrics.classification_report(y_validation, y_pred))
print (metrics.confusion_matrix(y_validation, y_pred))
print ('PD RandomForest AU ROC: ', metrics.roc_auc_score(y_validation,  clf.predict_proba(X_validation)[:,1] ))

print("Accuracy:",metrics.accuracy_score(y_validation, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97    303723
           1       0.01      0.57      0.01       202

   micro avg       0.94      0.94      0.94    303925
   macro avg       0.50      0.76      0.49    303925
weighted avg       1.00      0.94      0.97    303925

[[286140  17583]
 [    87    115]]
PD RandomForest AU ROC:  0.8276007779756849
Accuracy: 0.9418606564119437


In [41]:
# predict pCTR for each row of the validation set

pCTR = clf.predict_proba(X_validation)[:,1]  # αν εβαζες 0 θα ηταν το συμπληρωματικο το CTR
print(pCTR)

[0.45953433 0.38414397 0.3782576  ... 0.45782526 0.41153867 0.39128649]


In [42]:
# Perform Calibration because of the initial downsampling
predicted_CTR = pCTR/(pCTR+((1-pCTR)/w))
predicted_CTR

array([0.00616858, 0.00453278, 0.00442156, ..., 0.00612653, 0.0050793 ,
       0.00467059])